title: adolphshi
subtitle: 直面恐惧，创造未来
description: 直面恐惧，创造未来
keywords: null
author: adolphshi
language: zh-CN
timezone: Asia/Shanghai
url: http://adolphshi.github.io
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: admin/*
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
# syntax highlighter
shiki:
  theme: github-dark
  line_number: true # whether to show the line_number
syntax_highlighter: highlight.js
highlight:
  auto_detect: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
  exclude_languages:
    - example
  wrap: true
prismjs:
  enable: false
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: nexmoe
deploy:
  type: ''
# Markdown config
markdown:
  preset: "default"
  render:
    html: true
    xhtmlOut: false
    langPrefix: "language-"
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  enable_rules:
  disable_rules:
  plugins:
    - plugin:
      name: '@andatoshiki/markdown-it-katex'
      enable: true
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-checkbox
    - markdown-it-imsize
    - markdown-it-expandable
    - name: markdown-it-container
      options: success
    - name: markdown-it-container
      options: tips
    - name: markdown-it-container
      options: warning
    - name: markdown-it-container
      options: danger
  anchors:
    level: 2
    collisionSuffix: ""
    permalink: false
    permalinkClass: "header-anchor"
    permalinkSide: "left"
    permalinkSymbol: "¶"
    case: 0
    separator: "-"
aplayer:
  meting: true
encrypt: # hexo-blog-encrypt

  abstract: 有东西被加密了, 请输入密码查看.

  message: 您好, 这里需要密码.

  tags:

  - {name: 加密, password: 973060}

  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.

  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.
